apiVersion: apps/v1
kind: Deployment
metadata:
  name: Exo
  labels:
    app: Exo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Exo
  template:
    metadata:
      labels:
        app: Exo
    spec:
      containers:
        - name: Exo
          image: Exo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
