apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Exo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: Exo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: Exo-svc
                port:
                  number: 80
